SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
    FROM 
        (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
         UNION ALL
         SELECT FLAVOR, TOTAL_ORDER FROM JULY
         ) A
    GROUP BY FLAVOR
    ) B
ORDER BY TOTAL_SUM DESC
LIMIT 3;
